#!/usr/bin/env bash
set -e

export DEPLOY_ENV=GH_PAGES

npm run docs-gen

git config --global user.email nianqin.vip@gmail.com
git config --global user.name nianqin

mkdir -p ~/.ssh
chmod 600 ~/.ssh
ssh-keyscan github.com >> ~/.ssh/known_hosts

gh-pages -t -d docs-dist -b master -r git@github.com:nqdy666/fabric-map-vue.git
